CREATE TABLE IF NOT EXISTS public.documents (
  id                UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id           UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title             TEXT NOT NULL,
  description       TEXT,
  content_type      content_type NOT NULL DEFAULT 'article',
  url               TEXT,
  domain            TEXT,
  author            TEXT,
  published_at      TIMESTAMPTZ,
  estimated_read_time_minutes INTEGER,
  content_html      TEXT,
  content_text      TEXT,
  cover_image_url   TEXT,
  storage_path      TEXT,
  tags              TEXT[] NOT NULL DEFAULT '{}',
  is_favorite       BOOLEAN NOT NULL DEFAULT FALSE,
  is_archived       BOOLEAN NOT NULL DEFAULT FALSE,
  is_deleted        BOOLEAN NOT NULL DEFAULT FALSE,
  reading_progress  DECIMAL(5,2) NOT NULL DEFAULT 0,
  ai_summary        TEXT,
  ai_key_points     TEXT[],
  embedding         vector(1536),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_opened_at    TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.highlights (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id         UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  document_id     UUID NOT NULL REFERENCES public.documents(id) ON DELETE CASCADE,
  text            TEXT NOT NULL,
  note            TEXT,
  color           highlight_color NOT NULL DEFAULT 'yellow',
  location_data   JSONB NOT NULL DEFAULT '{}',
  tags            TEXT[] NOT NULL DEFAULT '{}',
  is_favorite     BOOLEAN NOT NULL DEFAULT FALSE,
  embedding       vector(1536),
  sr_due_date     TIMESTAMPTZ,
  sr_interval     INTEGER DEFAULT 0,
  sr_ease_factor  DECIMAL(4,2) DEFAULT 2.5,
  sr_repetitions  INTEGER DEFAULT 0,
  sr_status       review_status DEFAULT 'new',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
